### ISSUE TITLE
add capability to orchestrate user-defined "plans"

### ISSUE THREAD

**Issue by sgsullivan** [liquidweb/liquidweb-cli#24]
A user defined plan is defined as a saved set of commands (and their accompanying flags) to run in a specific order.

For example, this would empower users to do things like execute a plan automatically, to:

1.) Create 2 webserver nodes from a custom image named "web server"
2.) Create a loadbalancer pointing it at the 2 new nodes
3.) Create a database server from custom image "database server"
4.) Attach the 3 new servers to a private network

which for example, this could be orchestrated by running:

```
lw plan apply /path/to/plan.yaml
```

**Comment by dwburke** [comment]
base support is implemented, along with `cloud server create` and `cloud template restore`... closing this issue.. individual items can have support added over time
